version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: aupet-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - aupet-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: aupet-redis-ui
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - aupet-network

volumes:
  redis_data:
    driver: local

networks:
  aupet-network:
    driver: bridge