services:
  # Backend API Service
  - type: web
    name: auzap-backend-api
    runtime: node
    plan: starter
    region: oregon
    buildCommand: |
      cd backend &&
      npm ci --only=production &&
      npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://auzap-frontend.onrender.com
      - key: WEBHOOK_URL
        value: https://auzap-backend-api.onrender.com/api/webhook
    healthCheckPath: /health
    autoDeploy: true
    domains:
      - auzap-backend-api.onrender.com
    scaling:
      minInstances: 1
      maxInstances: 3
      targetCPUPercent: 70
      targetMemoryPercent: 80

  # Frontend Static Site
  - type: web
    name: auzap-frontend
    runtime: static
    plan: starter
    region: oregon
    buildCommand: |
      cd frontend &&
      echo "🧹 Limpando cache e dependências..." &&
      rm -rf dist node_modules/.cache .vite node_modules/.vite &&
      echo "📦 Instalando dependências com cache..." &&
      npm ci --prefer-offline --no-audit --no-fund &&
      echo "🔧 Configurando variáveis de ambiente..." &&
      export NODE_ENV=production &&
      export VITE_API_URL=https://auzap-backend-api.onrender.com/api &&
      echo "🚀 Executando build otimizado..." &&
      npm run build &&
      echo "📊 Gerando arquivo de versão..." &&
      echo '{"version":"'$(date +%s)'","timestamp":"'$(date)'","build":"render-optimized"}' > dist/version.json &&
      echo "📈 Análise do bundle (se disponível)..." &&
      ls -la dist/ &&
      du -sh dist/ &&
      echo "✅ Build concluído com sucesso!"
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://auzap-backend-api.onrender.com/api
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
    pullRequestPreviewsEnabled: true
    domains:
      - auzap-frontend.onrender.com
    headers:
      # HTML files - short cache for frequent updates
      - path: /
        name: Cache-Control
        value: public, max-age=0, s-maxage=3600, must-revalidate
      - path: /index.html
        name: Cache-Control
        value: public, max-age=0, s-maxage=3600, must-revalidate
      - path: "*.html"
        name: Cache-Control
        value: public, max-age=0, s-maxage=3600, must-revalidate

      # Static assets - long cache with versioning
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: "*.js"
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: "*.css"
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: "*.woff2"
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: "*.woff"
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: "*.ttf"
        name: Cache-Control
        value: public, max-age=31536000, immutable

      # Images - medium cache
      - path: "*.png"
        name: Cache-Control
        value: public, max-age=2592000
      - path: "*.jpg"
        name: Cache-Control
        value: public, max-age=2592000
      - path: "*.jpeg"
        name: Cache-Control
        value: public, max-age=2592000
      - path: "*.svg"
        name: Cache-Control
        value: public, max-age=2592000
      - path: "*.webp"
        name: Cache-Control
        value: public, max-age=2592000
      - path: "*.avif"
        name: Cache-Control
        value: public, max-age=2592000

      # API and dynamic content - no cache
      - path: /api/*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /version.json
        name: Cache-Control
        value: no-cache, no-store, must-revalidate

      # Security headers
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Permissions-Policy
        value: geolocation=(), microphone=(), camera=()
      - path: /*
        name: Strict-Transport-Security
        value: max-age=63072000; includeSubDomains; preload

      # Compression headers
      - path: /*
        name: Vary
        value: Accept-Encoding

databases:
  # Redis Cache for Sessions and Rate Limiting
  - name: auzap-redis
    plan: starter
    region: oregon
    maxmemoryPolicy: allkeys_lru