// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lytpeljmwjugsbapjkeb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5dHBlbGptd2p1Z3NiYXBqa2ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NTI3NDEsImV4cCI6MjA3NDQyODc0MX0.IfajDuzonzNXSrpni5_hwrWaT_7Yh8QthQq4bA7O-kc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});